- name: "Collect aws facts for instances in region '{{ region }}'"
  ec2_instance_info:
    region: "{{ region }}"
    filters: "{{ aws_inventory_filters }}"
  register: ansible_instance_facts
  check_mode: no

# - debug:
#     msg: "The OS Platform for image_id {{ target_image_id }} is {{ os_platform }}"   
#   loop: "{{ ansible_instance_facts.instances }}"
#   loop_control:
#     label: "{{ item.tags.Name }} - {{ item.instance_id }}"
#   vars:
#     # Find the image that matches the target_image_id and extract its os_platform
#     target_image_id: "{{ item.image_id }}"  # Replace with the desired image_id
#     os_platform: >-
#       {{
#         (aws_image | dict2items |
#           selectattr('value.' ~ region, 'equalto', target_image_id) |
#           map(attribute='value.os_platform') | first) | default('unknown')
#       }}

- name: Debug instance tags
  debug:
    msg: "{{ item.tags }}"
  loop: "{{ ansible_instance_facts.instances }}"

- name: Add instance to dynamic inventory
  add_host:
    hostname: "{{ item.tags.Name }}"

    ansible_host: "{{ item[return_address_for_ansible_host] if item.state.name == 'running' else '127.0.30.1' }}"
    ansible_ssh_private_key_file: "{{ aws_tmp_key }}"
    ansible_become_password: "{{ aws_inventory_ansible_user_password }}"
    ansible_user: "{{ 'sap_admin' if os_platform == 'windows' else aws_tmp_user }}"
    ansible_password: "{{ winrm_password if os_platform == 'windows' else '' }}"
    ansible_connection: "{{ 'winrm' if os_platform == 'windows' else 'ssh' }}"
    ansible_port: "{{ '5986' if os_platform == 'windows' else '22' }}"
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_become_method: "{{ 'runas' if os_platform == 'windows' else 'sudo' }}"
    
    groups:
      - "{{ aws_inventory_group }}"
      - "{{ env }}"
    region: "{{ region }}"
    ec2status: "{{ item }}"
    # host_data: per-host processed group_vars template inventory
    host_data: "{{ ( hostvars['localhost']['ec2']['hosts']
      | json_query(\"[?name=='\" + item.tags.Name + \"']\") )[0]
      | default({}) }}"
  changed_when: false
  loop: "{{ ansible_instance_facts.instances }}"
  loop_control:
    label: "{{ item.tags.Name }} - {{ item.instance_id }}/{{ aws_tmp_user }}"
  vars:
    target_image_id: "{{ item.image_id }}"  
    os_platform: >-
      {{
        (aws_image | dict2items |
          selectattr('value.' ~ region, 'equalto', target_image_id) |
          map(attribute='value.os_platform') | first) | default('unknown')
      }}
    aws_tmp_user: >-
      {{ aws_inventory_ansible_user
      if
        ( item.tags.Provision_status is defined and item.tags.Provision_status == 'done' ) 
      else
        aws_image_users[item.image_id] }}
    aws_tmp_key: >-
      {{ 'pipeline/secrets/id_rsa_ansible'
      if
        ( item.tags.Provision_status is defined and item.tags.Provision_status == 'done' ) 
      else
        'pipeline/secrets/id_rsa_deployer' }}
